Database: sql

SQL:
  DataSourceName: "user=postgres dbname=test password=mysecretpassword sslmode=disable"
  Driver: postgres

  Graphs:
    - Graph: TestGraph
      Vertices:
        - Table: users
          Label: users
          GidField: id

        - Table: products
          Label: products
          GidField: id

        - Table: purchases
          Label: purchases
          GidField: id

      Edges:
        - Table: purchase_items
          Label: purchasedProducts
          GidField: id
          From:
            SourceField: purchase_id
            DestTable: purchases
            DestField: id
          To:
            SourceField: product_id
            DestTable: products
            DestField: id

        - Table: ""
          Label: userPurchases          
          GidField: ""
          From:
            SourceField: ""
            DestTable: users
            DestField: id
          To:
            SourceField: ""
            DestTable: purchases
            DestField: user_id
