baseURL: https://bmeg.github.io/grip
canonifyURLs: true
languageCode: en-us
title: GRIP
publishDir: ../docs
menu:
  main:
    - name: API
      parent: Developers
      url: https://github.com/bmeg/grip/blob/master/gripql/gripql.proto
      weight: -100

    - name: GoDoc
      parent: Developers
      url: https://godoc.org/github.com/bmeg/grip
      weight: 100

security:
  funcs:
    getenv:
    - ^HUGO_
    - GRIP_VERSION